apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitops-dds-centros.fullname" . }}
  labels:
    {{- include "gitops-dds-centros.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port}} 
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "gitops-dds-centros.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitops-dds-centros.fullname" . }}-np
  labels:
    {{- include "gitops-dds-centros.labels" . | nindent 4 }}
spec:
  type: NodePort #{{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port}} 
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "gitops-dds-centros.selectorLabels" . | nindent 4 }}
