apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: click2call
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: temis
  project: default
  source:
    path: apps/click2call
    repoURL: git@github.com:pcarrascog/csj-gitops.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
