apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-cm
  labels:
    app: {{ .Chart.Name }}
data:
  default.conf: |-
    server {
      listen       80;
      listen  [::]:80;
      # server_name       clsj-desarrollo api-dev.devopschile.cl;
      server_name     clsj-desarrollo;
      server_tokens off;

      # proxy_set_header Origin $http_origin;
      # proxy_set_header Referer $http_referer;
      # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      # proxy_set_header X-Forwarded-Server $host;
      # proxy_set_header X-Host $http_host;
      # add_header Access-Control-Expose-Headers Date;

      location / {
        proxy_pass http://api:80/;
        server_tokens off;

        proxy_set_header Origin $http_origin;
        proxy_set_header Referer $http_referer;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Host $http_host;
        add_header Access-Control-Expose-Headers Date;

      }

    }
